// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// DO NOT EDIT!

package main

import (
	"github.com/pquerna/ffjson/inception"
	importedinceptionpackage "jmutate_go"
)

func main() {
	i := ffjsoninception.NewInception("jmutate.go", "jmutate_go", "jmutate_ffjson.go", false)
	i.AddMany(importedinceptionpackage.FFJSONExpose())
	i.Execute()
}
